version: "3.8"

services:
    fast1:
        build: .
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '2'
                    memory: '2G'
            placement:
                constraints:
                    - node.labels.type == slave1
        ports:
            - "8080:80"
        env_file:
            - .env
        volumes:
            - .:/project
    fast2:
        build: .
        deploy:
            mode: replicated
            replicas: 1
            resources:
                limits:
                    cpus: '2'
                    memory: '2G'
            placement:
                constraints:
                    - node.labels.type == slave2
        ports:
            - "8081:80"
        env_file:
            - .env
        volumes:
            - .:/project

    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: nginx
        container_name: container-lb
        ports:
            - "80:80"
        depends_on:
            - "fast1"
            - "fast2"
    db:
        image: mongo
        ports:
            - 6000:27017
        volumes:
            - taskdb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            #MONGO_INITDB_DATABASE: admin
volumes:
    taskdb: