version: "3.8"
services:
    fast1:
        build: .
        deploy:
            mode: replicated
            replicas: 2
            resources:
                limits:
                    cpus: '2'
                    memory: '2G'
        ports:
            - "8080"
        env_file:
            - .env
        volumes:
            - .:/project
    nginx:
        build:
            dockerfile: ./docker/nginx.dockerfile
            context: .
        image: nginx
        container_name: container-lb
        ports:
            - "80:80"
        depends_on:
            - "fast1"
    db:
        image: mongo:6.0
        ports:
            - 6000:27017
        volumes:
            - taskdb:/data/db
        environment:
            MONGO_INITDB_ROOT_USERNAME: admin
            MONGO_INITDB_ROOT_PASSWORD: password123
            #MONGO_INITDB_DATABASE: admin
volumes:
    taskdb: